#weixin:
#  appid: wxb801c03ab6bd02eb
#  appsecret: 7c5de93d9779b4a031b0cc0535686d35

# JWT相关配置
jwt.header: Authorization
# 过期时间
jwt.expiration: 864000
# 注意有一个空格
jwt.tokenHead: Bearer 

# wechat Auth
auth.wechat.sessionHost: https://api.weixin.qq.com/sns/jscode2session
auth.wechat.appId: wxb801c03ab6bd02eb
auth.wechat.secret: 7c5de93d9779b4a031b0cc0535686d35
auth.wechat.grantType: authorization_code